ARG VERSION=2.214-alpine
FROM jenkins/jenkins:${VERSION}
USER root
RUN wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.4.tgz \
    && tar xzvf docker-19.03.4.tgz \
    && cp docker/* /usr/bin/ \
    && rm -f docker-19.03.4.tgz
RUN curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" \
      -o /usr/bin/docker-compose \
    && chmod +x /usr/bin/docker-compose
